module.exports = {
    ATTEMPT_AUTH: "ATTEMPT_AUTH",
    ATTEMPT_AUTH_SUCCESS:"ATTEMPT_AUTH_SUCCESS",
    ATTEMPT_AUTH_FAIL:"ATTEMPT_AUTH_FAIL",
    LOAD_BRISTOL_PROVIDERS:"LOAD_BRISTOL_PROVIDERS",
    LOAD_BRISTOL_PROVIDERS_SUCCESS:"LOAD_BRISTOL_PROVIDERS_SUCCESS",
    LOAD_PROVIDER_FOR_EDITING:"LOAD_PROVIDER_FOR_EDITING",
    LOAD_PROVIDER_FOR_EDITING_SUCCESS:"LOAD_PROVIDER_FOR_EDITING_SUCCESS",
    SAVE_PROVIDER:"SAVE_PROVIDER",
    SAVE_PROVIDER_SUCCESS:"SAVE_PROVIDER_SUCCESS",
    DELETE_PROVIDER:"DELETE_PROVIDER",
    DELETE_PROVIDER_SUCCESS:"DELETE_PROVIDER_SUCCESS"
};